### ISSUE TITLE
System.BadImageFormatException : Could not resolve field token

### ISSUE THREAD

**Issue by stelcheck** [lucaslorentz/minicover#42]
I am experimenting with using `msbuild` and `minicover` on a Unity project to see if I could generate some coverage data. Without instrumentation, the test run fine, but with the instrumentation I get:

```plaintext
1) TestSelBase.TestSomething : System.TypeInitializationException : The type initializer for '<Module>' threw an exception.
  ----> System.BadImageFormatException : Could not resolve field token 0x0400000a
```

Let me know if I need to provide more details.

**Comment by bhugot** [comment]
how did you run your tests? with dotnet command?

**Comment by stelcheck** [comment]
I used nunit-console. Is there a specific method or protocol to follow for test execution on top of instrumentation?

**Comment by bhugot** [comment]
As this library is a netcoreapp so it can't be loaded outside netcoreapp at the moment

**Comment by TheAngryByrd** [comment]
I'm experiencing the similar error on netcoreapp2.0 and mono 5.10. I'm using expecto which doesn't use dotnet test but instead you call it with `dotnet run` or `mono`

Branch can be found here: https://github.com/TheAngryByrd/Hopac.Websockets/tree/codecov

To run it call `./codecov.sh`

netcoreapp2.0:

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for '<StartupCode$Hopac-Websockets-Tests>.$Tests' threw an exception. ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'dotnet-minicover, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   --- End of inner exception stack trace ---
   at Tests.tests@140-1.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at <StartupCode$Hopac-Websockets-Tests>.$Tests..cctor() in /Users/username/Documents/GitHub/Hopac.Websockets/tests/Hopac.Websockets.Tests/Tests.fs:line 138
   --- End of inner exception stack trace ---
   at Tests.get_tests()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at Expecto.Impl.getTestFromMemberInfo@1165-1.Invoke(a focusedState)
   at Expecto.Impl.testFromMember(MemberInfo mi)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@165.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Expecto.Impl.testFromType@1191.Invoke(Type t)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@165.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Expecto.Impl.testFromAssemblyWithFilter(FSharpFunc`2 typeFilter, Assembly a)
   at Expecto.Tests.runTestsInAssembly(ExpectoConfig config, String[] args)
```

mono

```
Unhandled Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for '<StartupCode$Hopac-Websockets-Tests>.$Tests' threw an exception. ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.BadImageFormatException: Could not resolve field token 0x0400000a, due to: Could not load type of field 'MiniCover.HitService:writers' (1) due to: Could not resolve type with token 01000014 (from typeref, class/assembly System.IO.StreamWriter, System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a) assembly:System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.IO.StreamWriter member:<none> assembly:/Users/username/Documents/GitHub/Hopac.Websockets/tests/Hopac.Websockets.Tests/bin/Release/net461/dotnet-minicover.dll type:HitService member:<none>
  at <Module>..cctor () [0x00000] in <5aa95b2fa1c21a6da74503832f5ba95a>:0
   --- End of inner exception stack trace ---
  at Tests+tests@140-1.GenerateNext (System.Collections.Generic.IEnumerable`1[Expecto.Test]& next) [0x00080] in <5aa95b345d4975a2a7450383345ba95a>:0
  at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1[T].MoveNextImpl () [0x00016] in <5a7203e1904cf4daa7450383e103725a>:0
  at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1[T].System-Collections-IEnumerator-MoveNext () [0x00000] in <5a7203e1904cf4daa7450383e103725a>:0
  at Microsoft.FSharp.Collections.SeqModule.ToList[T] (System.Collections.Generic.IEnumerable`1[T] source) [0x00063] in <5a7203e1904cf4daa7450383e103725a>:0
  at <StartupCode$Hopac-Websockets-Tests>.$Tests..cctor () [0x0002f] in <5aa95b345d4975a2a7450383345ba95a>:0
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at Tests.get_tests () [0x00000] in <5aa95b345d4975a2a7450383345ba95a>:0
  at System.Reflection.MonoProperty.StaticGetterAdapterFrame[R] (System.Reflection.MonoProperty+StaticGetter`1[R] getter, System.Object obj) [0x00000] in <ede5cf6930dc4b9a8366f15f6c89bbd0>:0
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x0005f] in <ede5cf6930dc4b9a8366f15f6c89bbd0>:0
   --- End of inner exception stack trace ---
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00073] in <ede5cf6930dc4b9a8366f15f6c89bbd0>:0
  at Expecto.Impl+getTestFromMemberInfo@1165-1[a,b].Invoke (a focusedState) [0x000ef] in <5a9db3dddf69a9a4a7450383ddb39d5a>:0
  at Microsoft.FSharp.Core.OptionModule.Map[T,TResult] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] mapping, Microsoft.FSharp.Core.FSharpOption`1[T] option) [0x0000c] in <5a7203e1904cf4daa7450383e103725a>:0
  at Expecto.Impl.testFromMember (System.Reflection.MemberInfo mi) [0x0000c] in <5a9db3dddf69a9a4a7450383ddb39d5a>:0
  at Expecto.Impl+testFromType@1196-1.Invoke (System.Reflection.MemberInfo mi) [0x00000] in <5a9db3dddf69a9a4a7450383ddb39d5a>:0
  at Microsoft.FSharp.Collections.Internal+IEnumerator+choose@165[TResult,T].System-Collections-IEnumerator-MoveNext () [0x00063] in <5a7203e1904cf4daa7450383e103725a>:0
  at Microsoft.FSharp.Collections.SeqModule.ToList[T] (System.Collections.Generic.IEnumerable`1[T] source) [0x0003f] in <5a7203e1904cf4daa7450383e103725a>:0
  at Expecto.Impl+testFromType@1191.Invoke (System.Type t) [0x00066] in <5a9db3dddf69a9a4a7450383ddb39d5a>:0
  at Microsoft.FSharp.Collections.Internal+IEnumerator+choose@165[TResult,T].System-Collections-IEnumerator-MoveNext () [0x00063] in <5a7203e1904cf4daa7450383e103725a>:0
  at Microsoft.FSharp.Collections.SeqModule.ToList[T] (System.Collections.Generic.IEnumerable`1[T] source) [0x0003f] in <5a7203e1904cf4daa7450383e103725a>:0
  at Expecto.Impl.testFromAssemblyWithFilter (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] typeFilter, System.Reflection.Assembly a) [0x00018] in <5a9db3dddf69a9a4a7450383ddb39d5a>:0
  at Expecto.Impl+testFromAssembly@1292-1.Invoke (System.Reflection.Assembly a) [0x00000] in <5a9db3dddf69a9a4a7450383ddb39d5a>:0
  at Expecto.Tests.runTestsInAssembly (Expecto.Impl+ExpectoConfig config, System.String[] args) [0x00086] in <5a9db3dddf69a9a4a7450383ddb39d5a>:0
```

**Comment by lucaslorentz** [comment]
@stelcheck 
Maybe your issue is already fixed on latest version, because @bhugot split the HitServices into a netstandard2.0 library.

**Comment by lucaslorentz** [comment]
@TheAngryByrd
Your issue should also be fixed by now.
Can you please try version 2.0.0-ci-20180318114828 and open other issues if necessary?

**Comment by lucaslorentz** [comment]
I'm closing this cause both reported issues seems to be fixed. Please, open new issues if necessary.
