### ISSUE TITLE
Unhandled Exception when running Minicover

### ISSUE THREAD

**Issue by mrjavaguy** [lucaslorentz/minicover#5]
`dotnet minicover instrument --workdir ../ --assemblies test/**/bin/**/*.dll --sources src/**/*.cs`

```
Instrumenting assembly "C:\dev\ims\SFMC\hubexchangegateway\test\Area.Admin.Tests\bin\Debug\netcoreapp2.0\Area.Admin.dll"

Unhandled Exception: System.Exception: Hash algorithm None is not supported.
   at MiniCover.Extensions.DocumentExtensions.CreateHashAlgorithm(DocumentHashAlgorithm algorithm)
   at MiniCover.Extensions.DocumentExtensions.FileHasChanged(Document document)
   at MiniCover.Instrumentation.Instrumenter.InstrumentAssembly(String assemblyFile)
   at MiniCover.Instrumentation.Instrumenter.Execute()
   at MiniCover.Program.<>c__DisplayClass0_0.<Main>b__1()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at MiniCover.Program.Main(String[] args)
```

Using `xunit` for unit tests.

Let me know what additional information you might need or how I can go about debugging this.

**Comment by lucaslorentz** [comment]
Hey, it seems that your pdb files doesn't contain hash of source files.

That shouldn't be a problem, I use that just to check if the source file was modified after compiled.

I changed the code to don't fail if there is no hash, can you please try again with new version?

MiniCover 2.0.0-ci-20180117202753

**Comment by mrjavaguy** [comment]
Well that got me past this issue. So I am going to close and open a new issue.
