### ISSUE TITLE
Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'DataExtensions.. when dll is in the directory.

### ISSUE THREAD

**Issue by mrjavaguy** [lucaslorentz/minicover#6]
Received this after calling `dotnet minicover instrument --workdir ../ --assemblies test/**/bin/**/*.dll --sources src/**/*.cs`

```
Instrumenting assembly "C:\dev\ims\SFMC\hubexchangegateway\test\Area.Journeys.Tests\bin\Release\netcoreapp2.0\Area.Journeys.dll"                               
Instrumenting assembly "C:\dev\ims\SFMC\hubexchangegateway\test\Area.Journeys.Tests\bin\Release\netcoreapp2.0\Common.dll"                                      
Instrumenting assembly "C:\dev\ims\SFMC\hubexchangegateway\test\Area.Journeys.Tests\bin\Release\netcoreapp2.0\DataExtensions.dll"                              
Instrumenting assembly "C:\dev\ims\SFMC\hubexchangegateway\test\Area.Journeys.Tests\bin\Release\netcoreapp2.0\MarketingCloudCommands.dll"                      
Instrumenting assembly "C:\dev\ims\SFMC\hubexchangegateway\test\Area.Journeys.Tests\bin\Release\netcoreapp2.0\Nexxus.MarketingCloud.dll"                       
Instrumenting assembly "C:\dev\ims\SFMC\hubexchangegateway\test\Area.Journeys.Tests\bin\Release\netcoreapp2.0\Nexxus.MarketingCloud.Soap.dll"                  
Instrumenting assembly "C:\dev\ims\SFMC\hubexchangegateway\test\Area.PreferenceCenter.Tests\bin\Release\netcoreapp2.0\Area.PreferenceCenter.dll"               
                                                                                                                                                               
Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'DataExtensions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
'                                                                                                                                                              
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)                                                         
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)                                                                                   
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)                                                                                                  
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)                                                                                                      
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)                                                                 
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)                                                                      
   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)                                                
   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)                                                                                        
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)                                                                                            
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)                                                                                               
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)                                                                                                  
   at Mono.Cecil.MetadataBuilder.AddTypes()                                                                                                                    
   at Mono.Cecil.MetadataBuilder.BuildTypes()                                                                                                                  
   at Mono.Cecil.MetadataBuilder.BuildModule()                                                                                                                 
   at Mono.Cecil.MetadataBuilder.BuildMetadata()                                                                                                               
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)                                                             
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)                                                                                    
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)                                                                 
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)                                                 
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)                                           
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)                                                                          
   at MiniCover.Instrumentation.Instrumenter.InstrumentAssembly(String assemblyFile)                                                                           
   at MiniCover.Instrumentation.Instrumenter.Execute()                                                                                                         
   at MiniCover.Program.<>c__DisplayClass0_0.<Main>b__1()                                                                                                      
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)                                                                      
   at MiniCover.Program.Main(String[] args)                                                                                                                    
```

Looking in the test/bin directory I see that dll in there
![image](https://user-images.githubusercontent.com/2294035/35073242-f804a54a-fb9c-11e7-9500-35f3b1482ef7.png)

**Comment by mrjavaguy** [comment]
Note: if I add `--exclude-assemblies **/dataextensions.dll` to the command line, I still get the error.

**Comment by mrjavaguy** [comment]
I was able to continue by excluding Area.PreferenceCenter.dll but ran into another issue, that I know how to get around but I think should be fixed 
```
Executing: "C:/Program Files/dotnet/dotnet.exe" minicover reset

Unhandled Exception: System.Exception: Coverage file coverage.json doesn't exist
   at MiniCover.Program.LoadCoverageFile(String coverageFile)
   at MiniCover.Program.<>c__DisplayClass0_4.<Main>b__9()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at MiniCover.Program.Main(String[] args)
```

**Comment by lucaslorentz** [comment]
I guess this should fix the assembly loading issue:
https://groups.google.com/forum/#!topic/mono-cecil/2YrccvV3dpY

I'm setting up a scenario and will fix it.

**Comment by lucaslorentz** [comment]
I just added tests with referenced assemblies, but it works, no errors.

Is that picture from folder `C:\dev\ims\SFMC\hubexchangegateway\test\Area.PreferenceCenter.Tests\bin\Release\netcoreapp2.0\`?

I think Cecil searches for it there.

**Comment by mrjavaguy** [comment]
The picture is from that directory, I am trying to figure out what is different about that project, out of twenty or so in the solution it is the only having issues.

**Comment by lucaslorentz** [comment]
@mrjavaguy 
I merged your PRs, I believe this issue is completely fixed. Thanks.
