### ISSUE TITLE
System.InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by Valeriy1991** [lucaslorentz/minicover#70]
Hello!

When I'm trying use assemby instrumenting with last build (**2.0.0-ci-20180325225037**) , I've got an error:
```
Unhandled Exception: 
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Mono.Cecil.Cil.IlProcessorExtensions.EncapsulateMethodBodyWithTryFinallyBlock(ILProcessor ilProcessor, Instruction firstInstruction, Action`2 insertBeforReturn)
   at MiniCover.Instrumentation.Instrumenter.InstrumentMethod(MethodDefinition methodDefinition, IEnumerable`1 sequencePoints, TypeReference methodContextClassReference, MethodReference enterM
ethodReference, MethodReference exitMethodReference, String[] fileLines, InstrumentedAssembly instrumentedAssembly, String sourceRelativePath, MethodReference hitInstructionReference)
   at MiniCover.Instrumentation.Instrumenter.InstrumentAssemblyIfNecessary(String assemblyFile)
   at MiniCover.Instrumentation.Instrumenter.VisitAssemblyGroup(IEnumerable`1 assemblyFiles)
   at MiniCover.Instrumentation.Instrumenter.Execute()
   at MiniCover.Program.<>c__DisplayClass0_1.<Main>b__8()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at MiniCover.Program.Main(String[] args)
```
I'm run assemblies instrumenting with this powershell command:
```powershell
	cd .\tools\CustomProjectName.Tools
	dotnet minicover instrument --workdir ../../ --assemblies **/.\tests/**/bin/**/*.dll --sources ../..//**/*.cs --coverage-file minicover-coverage.json
	dotnet minicover reset
	cd ../..
```
In version **2.0.0-ci-20180321193925** analysis of code coverage finished successfully

**Comment by bhugot** [comment]
Hello, Is your code on github please? There is something wrong with the IL of a constructor in one of your class.

**Comment by Valeriy1991** [comment]
@bhugot ok, I will try debug instrumenting of my code...

**Comment by bhugot** [comment]
Found the problem with static constructor. Will do a fix still there use previous version please

**Comment by Valeriy1991** [comment]
While debug I'm found that exception was occured at line (*):
```
        private static Instruction GetFirstConstructorInstruction(MethodBody body)
        {
            var constructorInstruction = body.Instructions.First(a => a.OpCode == OpCodes.Call); // (*)
            return constructorInstruction;
        }
```
for constructor of this class:
```
    public class TargetRequestStatusesForExecutingJobQuery : DbQuery<List<RequestStatus>>
    {
        public TargetRequestStatusesForExecutingJobQuery(IDbExecutor dbExecutor) : base(dbExecutor)
        {
        }
        public override List<RequestStatus> Get()
        {
            // Some logic
        }
    }
```
where DbQuery - is class from my other Nuget-package that I'm place in this GitHub repository: https://github.com/Valeriy1991/CQRSlight/blob/master/CQRSlight.Db/Abstract/DbQuery.cs

I note that `body.Instructions` has 15 items.

**Comment by bhugot** [comment]
could you try again with #73

**Comment by bhugot** [comment]
please try version 2.0.0-ci-20180328123752

**Comment by Valeriy1991** [comment]
@bhugot This problem was fixed, thanks!
