### ISSUE TITLE
System.NotImplementedException: GenericInst with 2.0.0-ci-20180328123752

### ISSUE THREAD

**Issue by tijanacosovic** [lucaslorentz/minicover#91]
Hi,

I am trying to implement this in my pipeline but I am getting:

Unhandled Exception: System.NotImplementedException: GenericInst
   at Mono.Cecil.SignatureReader.ReadPrimitiveValue(ElementType type)
   at Mono.Cecil.MetadataReader.ReadLocalConstant(UInt32 rid)
   at Mono.Cecil.MetadataReader.ReadLocalScope(Row`6 record)
   at Mono.Cecil.MetadataReader.ReadScope(MethodDefinition method)
   at Mono.Cecil.Cil.PortablePdbReader.Read(MethodDefinition method)
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.MethodDefinition.get_DebugInformation()
   at MiniCover.Extensions.TypeDefinitionExtensions.<>c.<GetAllMethods>b__1_0(MethodDefinition m)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at MiniCover.Extensions.TypeDefinitionExtensions.<GetAllMethods>d__1.MoveNext()
   at MiniCover.Extensions.TypeDefinitionExtensions.<GetAllMethods>d__1.MoveNext()
   at MiniCover.Extensions.AssemblyDefinitionExtensions.<GetAllMethods>d__0.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at MiniCover.Instrumentation.Instrumenter.InstrumentAssemblyIfNecessary(String assemblyFile)
   at MiniCover.Instrumentation.Instrumenter.VisitAssemblyGroup(IEnumerable`1 assemblyFiles)
   at MiniCover.Instrumentation.Instrumenter.Execute()
   at MiniCover.Program.<>c__DisplayClass0_1.<Main>b__8()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at MiniCover.Program.Main(String[] args)

**Comment by lucaslorentz** [comment]
Could you please provide the project you tried to measure code coverage?
Or try again with the latest version `3.0.1`?

**Comment by lucaslorentz** [comment]
This seems to be fixed by mono cecil.
